# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/pixiu/commerce/models/category/columns.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Category

# List Title
title: pixiu.commerce::lang.models.category

# Link URL for each record
recordUrl: pixiu/commerce/categories/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Show tree
showTree: true
treeExpanded: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_categories_toolbar

    # Search widget configuration
    search:
        prompt: Search bro