# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: pixiu.commerce::lang.models.category

# Model Form Field configuration
form: $/pixiu/commerce/models/category/fields.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Category

# Default redirect location
defaultRedirect: pixiu/commerce/categories

# Create page
create:
    title: pixiu.commerce::lang.models.category
    redirect: pixiu/commerce/categories/update/:id
    redirectClose: pixiu/commerce/categories

# Update page
update:
    title: pixiu.commerce::lang.models.category
    redirect: pixiu/commerce/categories
    redirectClose: pixiu/commerce/categories

# Preview page
preview:
    title: pixiu.commerce::lang.models.category
