addresses:
    label: pixiu.commerce::lang.fields.address
    manage:
        form: $/pixiu/commerce/models/address/fields.yaml
        list: $/pixiu/commerce/models/address/columns.yaml
    view:
        list: $/pixiu/commerce/models/address/columns.yaml
        toolbarButtons: create|delete

orders:
    label: pixiu.commerce::lang.fields.order
    readOnly: true
    view:
        list: $/pixiu/commerce/models/order/columns.yaml
        recordUrl: pixiu/commerce/orders/preview/:id