# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: pixiu.commerce::lang.models.user

# Model Form Field configuration
form: $/pixiu/commerce/models/user/fields.yaml

# Model Class name
modelClass: Rainlab\User\Models\User

# Default redirect location
defaultRedirect: pixiu/commerce/users

# Create page
create:
    title: pixiu.commerce::lang.models.user
    redirect: pixiu/commerce/users/update/:id
    redirectClose: pixiu/commerce/users

# Update page
update:
    title: pixiu.commerce::lang.models.user
    redirect: pixiu/commerce/users
    redirectClose: pixiu/commerce/users

# Preview page
preview:
    title: pixiu.commerce::lang.models.user
