addresses:
    label: pixiu.commerce::lang.fields.address
    manage:
        form: $/pixiu/commerce/models/address/fields.yaml
        list: $/pixiu/commerce/models/address/columns.yaml
    view:
        list: $/pixiu/commerce/models/address/columns.yaml
        toolbarButtons: create|delete