# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: pixiu.commerce::lang.models.brand

# Model Form Field configuration
form: $/pixiu/commerce/models/brand/fields.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Brand

# Default redirect location
defaultRedirect: pixiu/commerce/brands

# Create page
create:
    title: pixiu.commerce::lang.models.brand
    redirect: pixiu/commerce/brands/update/:id
    redirectClose: pixiu/commerce/brands

# Update page
update:
    title: pixiu.commerce::lang.models.brand
    redirect: pixiu/commerce/brands
    redirectClose: pixiu/commerce/brands

# Preview page
preview:
    title: pixiu.commerce::lang.models.brand
