# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Order

# Model Form Field configuration
form: $/pixiu/commerce/models/order/fields.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Order

# Default redirect location
defaultRedirect: pixiu/commerce/orders

# Create page
create:
    title: Create Order
    redirect: pixiu/commerce/orders/update/:id
    redirectClose: pixiu/commerce/orders

# Update page
update:
    title: Edit Order
    redirect: pixiu/commerce/orders
    redirectClose: pixiu/commerce/orders

# Preview page
preview:
    title: Preview Order
    form: $/pixiu/commerce/models/order/preview_fields.yaml
