# ===================================
#  Relation Behavior Config
# ===================================

logs:
    label: log
    view:
        list: $/pixiu/commerce/models/orderlog/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/pixiu/commerce/models/orderlog/fields.yaml
        recordsPerPage: 10