# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Tax

# Model Form Field configuration
form: $/pixiu/commerce/models/tax/fields.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Tax

# Default redirect location
defaultRedirect: pixiu/commerce/taxes

# Create page
create:
    title: Create Tax
    redirect: pixiu/commerce/taxes/update/:id
    redirectClose: pixiu/commerce/taxes

# Update page
update:
    title: Edit Tax
    redirect: pixiu/commerce/taxes
    redirectClose: pixiu/commerce/taxes

# Preview page
preview:
    title: Preview Tax
