# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: pixiu.commerce::lang.models.tax

# Model Form Field configuration
form: $/pixiu/commerce/models/tax/fields.yaml

# Model Class name
modelClass: Pixiu\Commerce\Models\Tax

# Default redirect location
defaultRedirect: pixiu/commerce/taxes

# Create page
create:
    title: pixiu.commerce::lang.models.tax
    redirect: pixiu/commerce/taxes/update/:id
    redirectClose: pixiu/commerce/taxes

# Update page
update:
    title: pixiu.commerce::lang.models.tax
    redirect: pixiu/commerce/taxes
    redirectClose: pixiu/commerce/taxes

# Preview page
preview:
    title: pixiu.commerce::lang.models.tax
